# Generated by Django 5.2.14 on 2026-08-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='products/')),
                ('features', models.TextField(help_text='Enter features separated by a comma (e.g., High Efficiency, Durable, Long Warranty)')),
                ('link_url', models.CharField(default='#', max_length=200)),
            ],
        ),
    ]
