# Generated by Django 6.1 on 2026-08-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productcard_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='link_url',
        ),
    ]
