# Generated by Django 6.1 on 2026-08-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(help_text='e.g., 03:45', max_length=20)),
                ('video_thumbnail', models.ImageField(upload_to='media_center/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='media_center/news/')),
                ('category', models.CharField(help_text='e.g., Company News, Industry Insights, Technology', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media_center/gallery/')),
                ('is_secondary', models.BooleanField(default=False, help_text='Check if this image goes to the right side smaller grid')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
