# Generated by Django 6.1 on 2026-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredvideo',
            name='url',
            field=models.URLField(default=1, help_text='Link to the video (e.g., YouTube, Vimeo)'),
            preserve_default=False,
        ),
    ]
