# Generated by Django 6.1 on 2026-08-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutioncard',
            name='icon_class',
        ),
    ]
