# Generated by Django 6.1 on 2026-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g., Residential, Commercial, Industrial, Utility Scale', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='e.g., Bengaluru, Karnataka', max_length=100)),
                ('capacity', models.CharField(help_text='e.g., 10 kW', max_length=50)),
                ('capacity_label', models.CharField(default='Capacity', max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('year_label', models.CharField(default='Year', max_length=50)),
                ('project_image', models.ImageField(upload_to='projects/')),
            ],
        ),
        migrations.CreateModel(
            name='FounderVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_prefix', models.CharField(help_text="Text before the green highlighted text (e.g., 'A Vision That')", max_length=100)),
                ('heading_highlight', models.CharField(help_text="Green highlighted text (e.g., 'Powers Change')", max_length=100)),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField()),
                ('founder_image', models.ImageField(upload_to='founder/')),
                ('quote_text', models.TextField()),
                ('quote_author', models.CharField(help_text='e.g., Arjun Reddy', max_length=100)),
                ('quote_author_title', models.CharField(help_text='e.g., Founder & CEO, Nuetech Solar', max_length=150)),
                ('button_text', models.CharField(default='Know More About Our Journey', max_length=100)),
            ],
        ),
    ]
