# Generated by Django 6.1 on 2026-08-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(default='Full Time', max_length=100)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
